### ISSUE TITLE
作者您好，这个代码我能跑通，然后输了验证码总是登录失败

### ISSUE THREAD

**Issue by FantasticRhythm** [A2u13/SCUCourseSelectHelper#8]
我看了下源码，应该是session.post（__, _, _）的返回值是没有“欢迎你”，然后我不清楚是你post的问题，还是 服务器的返回值的问题

**Comment by lkccu** [comment]
能解决这个问题了嘛

**Comment by Vinkle-hzt** [comment]
教务处在登录api里面加了个tokenValue，原脚本暂时不能用了
